/**
 * Provinces Seed Data
 * Seeds all 63 Vietnamese provinces with historical eras and resource configurations
 * Historical Eras: Ancient → Dynasty → Medieval → Modern → Contemporary
 */

import { Client } from 'pg'

interface Province {
  id: number
  name: string
  name_english: string
  region: string
  historical_eras: string[] // 5 eras per province
  base_gold_rate: number
  base_rice_rate: number
  base_wood_rate: number
  base_stone_rate: number
  base_bazan_rate: number
  is_capital: boolean
  unlock_order: number // Order of unlock in story progression
  unlock_story_day: number // Which day story to unlock this province
}

// All 63 Vietnamese provinces with historical data
const PROVINCES_DATA: Province[] = [
  // NORTHERN REGION (Bắc Bộ) - 15 provinces
  {
    id: 1,
    name: 'Hà Nội',
    name_english: 'Hanoi',
    region: 'North Central',
    historical_eras: ['Khởi Nguyên Việt (2879 BCE)', 'Thăng Long (1010 CE)', 'Trần Dynasty (1200s)', 'Lê Dynasty (1400s)', 'Modern Hanoi (1954+)'],
    base_gold_rate: 150,
    base_rice_rate: 120,
    base_wood_rate: 80,
    base_stone_rate: 100,
    base_bazan_rate: 30,
    is_capital: true,
    unlock_order: 1,
    unlock_story_day: 0, // Starting province
  },
  {
    id: 2,
    name: 'Hải Phòng',
    name_english: 'Hai Phong',
    region: 'North Central',
    historical_eras: ['Ancient Port (2000 BCE)', 'Trading Hub (1000 CE)', 'Commerce Era (1200s)', 'Colonial Port (1800s)', 'Modern Port (1950+)'],
    base_gold_rate: 130,
    base_rice_rate: 110,
    base_wood_rate: 100,
    base_stone_rate: 90,
    base_bazan_rate: 25,
    is_capital: false,
    unlock_order: 2,
    unlock_story_day: 5,
  },
  {
    id: 3,
    name: 'Vĩnh Phúc',
    name_english: 'Vinh Phuc',
    region: 'North Central',
    historical_eras: ['Ancient Settlement (2500 BCE)', 'Kingdom Period (1000 CE)', 'Medieval City (1300s)', 'French Colony (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 100,
    base_rice_rate: 140,
    base_wood_rate: 110,
    base_stone_rate: 70,
    base_bazan_rate: 20,
    is_capital: false,
    unlock_order: 3,
    unlock_story_day: 7,
  },
  {
    id: 4,
    name: 'Bắc Ninh',
    name_english: 'Bac Ninh',
    region: 'North Central',
    historical_eras: ['Ancient Tribe (2000 BCE)', 'Ming Occupation (1400s)', 'Trần Glory (1200s)', 'French Rule (1800s)', 'Modern Bac Ninh (1950+)'],
    base_gold_rate: 95,
    base_rice_rate: 150,
    base_wood_rate: 100,
    base_stone_rate: 60,
    base_bazan_rate: 15,
    is_capital: false,
    unlock_order: 4,
    unlock_story_day: 10,
  },
  {
    id: 5,
    name: 'Bắc Giang',
    name_english: 'Bac Giang',
    region: 'North Central',
    historical_eras: ['Bronze Age (1500 BCE)', 'Han Dynasty (100 BCE)', 'Ly Dynasty (1000 CE)', 'Ming Invasion (1400s)', 'Modern Era (1950+)'],
    base_gold_rate: 85,
    base_rice_rate: 130,
    base_wood_rate: 120,
    base_stone_rate: 50,
    base_bazan_rate: 12,
    is_capital: false,
    unlock_order: 5,
    unlock_story_day: 12,
  },
  {
    id: 6,
    name: 'Quảng Ninh',
    name_english: 'Quang Ninh',
    region: 'North Central',
    historical_eras: ['Coastal Kingdom (2000 BCE)', 'Port of Han (100 BCE)', 'Trần Maritime (1200s)', 'Halong Bay (1300s)', 'Modern Port (1950+)'],
    base_gold_rate: 120,
    base_rice_rate: 90,
    base_wood_rate: 150,
    base_stone_rate: 110,
    base_bazan_rate: 35,
    is_capital: false,
    unlock_order: 6,
    unlock_story_day: 15,
  },
  {
    id: 7,
    name: 'Lạng Sơn',
    name_english: 'Lang Son',
    region: 'Northeast',
    historical_eras: ['Border Tribe (2500 BCE)', 'Ngũ Lĩnh (1000 CE)', 'Ming Border (1400s)', 'French Territory (1800s)', 'Modern Border (1950+)'],
    base_gold_rate: 70,
    base_rice_rate: 100,
    base_wood_rate: 130,
    base_stone_rate: 140,
    base_bazan_rate: 28,
    is_capital: false,
    unlock_order: 7,
    unlock_story_day: 18,
  },
  {
    id: 8,
    name: 'Tuyên Quang',
    name_english: 'Tuyen Quang',
    region: 'Northeast',
    historical_eras: ['Mountain Tribe (2000 BCE)', 'Tây Sơn War (1700s)', 'French Indochina (1800s)', 'Revolution (1945)', 'Modern Province (1950+)'],
    base_gold_rate: 60,
    base_rice_rate: 110,
    base_wood_rate: 140,
    base_stone_rate: 130,
    base_bazan_rate: 25,
    is_capital: false,
    unlock_order: 8,
    unlock_story_day: 21,
  },
  {
    id: 9,
    name: 'Cao Bằng',
    name_english: 'Cao Bang',
    region: 'Northeast',
    historical_eras: ['Ancient Mountain (2500 BCE)', 'Bạch Đằng (1288)', 'Ming Invasion (1400s)', 'French Colony (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 75,
    base_rice_rate: 95,
    base_wood_rate: 150,
    base_stone_rate: 120,
    base_bazan_rate: 30,
    is_capital: false,
    unlock_order: 9,
    unlock_story_day: 24,
  },
  {
    id: 10,
    name: 'Bắc Kạn',
    name_english: 'Bac Kan',
    region: 'Northeast',
    historical_eras: ['Forest Kingdom (2000 BCE)', 'Kingdom Period (1000 CE)', 'Ming War (1400s)', 'French Indochina (1800s)', 'Modern Era (1950+)'],
    base_gold_rate: 65,
    base_rice_rate: 100,
    base_wood_rate: 160,
    base_stone_rate: 100,
    base_bazan_rate: 22,
    is_capital: false,
    unlock_order: 10,
    unlock_story_day: 26,
  },
  {
    id: 11,
    name: 'Thái Nguyên',
    name_english: 'Thai Nguyen',
    region: 'Northeast',
    historical_eras: ['Ethnic Kingdom (2000 BCE)', 'Tây Sơn (1700s)', 'French Mining (1800s)', 'Steel Industry (1900s)', 'Modern Industrial (1950+)'],
    base_gold_rate: 110,
    base_rice_rate: 100,
    base_wood_rate: 130,
    base_stone_rate: 80,
    base_bazan_rate: 32,
    is_capital: false,
    unlock_order: 11,
    unlock_story_day: 28,
  },
  {
    id: 12,
    name: 'Yên Bái',
    name_english: 'Yen Bai',
    region: 'Northwest',
    historical_eras: ['Ancient Tribe (2500 BCE)', 'Kingdom Expansion (1000 CE)', 'Ming Period (1400s)', 'French Territory (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 80,
    base_rice_rate: 95,
    base_wood_rate: 140,
    base_stone_rate: 110,
    base_bazan_rate: 26,
    is_capital: false,
    unlock_order: 12,
    unlock_story_day: 30,
  },
  {
    id: 13,
    name: 'Sơn La',
    name_english: 'Son La',
    region: 'Northwest',
    historical_eras: ['Ethnic Settlement (2000 BCE)', 'Highland Kingdom (1000 CE)', 'Ming Conquest (1400s)', 'French Fort (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 70,
    base_rice_rate: 90,
    base_wood_rate: 150,
    base_stone_rate: 100,
    base_bazan_rate: 24,
    is_capital: false,
    unlock_order: 13,
    unlock_story_day: 32,
  },
  {
    id: 14,
    name: 'Điện Biên',
    name_english: 'Dien Bien',
    region: 'Northwest',
    historical_eras: ['Border Kingdom (2000 BCE)', 'Ancient Trail (1000 CE)', 'French Fortress (1900s)', 'Vietnam Victory (1954)', 'Modern Province (1950+)'],
    base_gold_rate: 75,
    base_rice_rate: 85,
    base_wood_rate: 160,
    base_stone_rate: 130,
    base_bazan_rate: 28,
    is_capital: false,
    unlock_order: 14,
    unlock_story_day: 34,
  },
  {
    id: 15,
    name: 'Lai Châu',
    name_english: 'Lai Chau',
    region: 'Northwest',
    historical_eras: ['Mountain Tribe (2500 BCE)', 'Highland Kingdom (1000 CE)', 'Chinese Border (1400s)', 'French Territory (1800s)', 'Modern Border (1950+)'],
    base_gold_rate: 65,
    base_rice_rate: 80,
    base_wood_rate: 170,
    base_stone_rate: 120,
    base_bazan_rate: 25,
    is_capital: false,
    unlock_order: 15,
    unlock_story_day: 36,
  },

  // CENTRAL HIGHLANDS (Tây Nguyên) - 5 provinces
  {
    id: 16,
    name: 'Lâm Đồng',
    name_english: 'Lam Dong',
    region: 'Central Highlands',
    historical_eras: ['Ancient Forest (2000 BCE)', 'Kingdom Expansion (1000 CE)', 'Champa War (1300s)', 'French Colony (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 100,
    base_rice_rate: 100,
    base_wood_rate: 150,
    base_stone_rate: 70,
    base_bazan_rate: 30,
    is_capital: false,
    unlock_order: 16,
    unlock_story_day: 38,
  },
  {
    id: 17,
    name: 'Đắk Lắk',
    name_english: 'Dak Lak',
    region: 'Central Highlands',
    historical_eras: ['Ethnic Land (2000 BCE)', 'Champa Kingdom (1000 CE)', 'Vietnam Expansion (1600s)', 'French Indochina (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 90,
    base_rice_rate: 120,
    base_wood_rate: 140,
    base_stone_rate: 80,
    base_bazan_rate: 28,
    is_capital: false,
    unlock_order: 17,
    unlock_story_day: 40,
  },
  {
    id: 18,
    name: 'Đắk Nông',
    name_english: 'Dak Nong',
    region: 'Central Highlands',
    historical_eras: ['Forest Kingdom (2000 BCE)', 'Champa War (1000 CE)', 'Vietnam Expansion (1600s)', 'French Territory (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 85,
    base_rice_rate: 110,
    base_wood_rate: 150,
    base_stone_rate: 75,
    base_bazan_rate: 26,
    is_capital: false,
    unlock_order: 18,
    unlock_story_day: 42,
  },
  {
    id: 19,
    name: 'Gia Lai',
    name_english: 'Gia Lai',
    region: 'Central Highlands',
    historical_eras: ['Ethnic Settlement (2000 BCE)', 'Champa Kingdom (1000 CE)', 'Tây Sơn War (1700s)', 'French Colony (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 80,
    base_rice_rate: 100,
    base_wood_rate: 160,
    base_stone_rate: 90,
    base_bazan_rate: 25,
    is_capital: false,
    unlock_order: 19,
    unlock_story_day: 44,
  },
  {
    id: 20,
    name: 'Kon Tum',
    name_english: 'Kon Tum',
    region: 'Central Highlands',
    historical_eras: ['Mountain Kingdom (2000 BCE)', 'Champa Border (1000 CE)', 'France Fort (1900s)', 'Vietnam War (1950s-60s)', 'Modern Province (1950+)'],
    base_gold_rate: 75,
    base_rice_rate: 95,
    base_wood_rate: 170,
    base_stone_rate: 100,
    base_bazan_rate: 27,
    is_capital: false,
    unlock_order: 20,
    unlock_story_day: 46,
  },

  // CENTRAL COAST (Duyên Hải Trung Bộ) - 8 provinces
  {
    id: 21,
    name: 'Thanh Hóa',
    name_english: 'Thanh Hoa',
    region: 'Central Coast',
    historical_eras: ['Ancient Port (2000 BCE)', 'Champa War (1000 CE)', 'Trần Dynasty (1200s)', 'French Indochina (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 110,
    base_rice_rate: 140,
    base_wood_rate: 100,
    base_stone_rate: 80,
    base_bazan_rate: 28,
    is_capital: false,
    unlock_order: 21,
    unlock_story_day: 48,
  },
  {
    id: 22,
    name: 'Nghệ An',
    name_english: 'Nghe An',
    region: 'Central Coast',
    historical_eras: ['Ancient Land (2000 BCE)', 'Champa Kingdom (1000 CE)', 'Tây Sơn Revolt (1700s)', 'French Colony (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 100,
    base_rice_rate: 130,
    base_wood_rate: 110,
    base_stone_rate: 70,
    base_bazan_rate: 26,
    is_capital: false,
    unlock_order: 22,
    unlock_story_day: 50,
  },
  {
    id: 23,
    name: 'Hà Tĩnh',
    name_english: 'Ha Tinh',
    region: 'Central Coast',
    historical_eras: ['Coastal Kingdom (2000 BCE)', 'Champa War (1000 CE)', 'Tây Sơn Base (1700s)', 'French Territory (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 95,
    base_rice_rate: 120,
    base_wood_rate: 100,
    base_stone_rate: 75,
    base_bazan_rate: 24,
    is_capital: false,
    unlock_order: 23,
    unlock_story_day: 52,
  },
  {
    id: 24,
    name: 'Quảng Bình',
    name_english: 'Quang Binh',
    region: 'Central Coast',
    historical_eras: ['Ancient Port (2000 BCE)', 'Champa War (1000 CE)', 'Caves Kingdom (1300s)', 'French Fort (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 100,
    base_rice_rate: 115,
    base_wood_rate: 120,
    base_stone_rate: 90,
    base_bazan_rate: 29,
    is_capital: false,
    unlock_order: 24,
    unlock_story_day: 54,
  },
  {
    id: 25,
    name: 'Quảng Trị',
    name_english: 'Quang Tri',
    region: 'Central Coast',
    historical_eras: ['Coastal Settlement (2000 BCE)', 'Champa War (1000 CE)', 'Seventeenth Division (1600s)', 'Vietnam War (1950s-60s)', 'Modern Province (1950+)'],
    base_gold_rate: 90,
    base_rice_rate: 110,
    base_wood_rate: 130,
    base_stone_rate: 100,
    base_bazan_rate: 27,
    is_capital: false,
    unlock_order: 25,
    unlock_story_day: 56,
  },
  {
    id: 26,
    name: 'Thừa Thiên - Huế',
    name_english: 'Thua Thien - Hue',
    region: 'Central Coast',
    historical_eras: ['Ancient Port (2000 BCE)', 'Champa Capital (1000 CE)', 'Imperial Court (1600s)', 'Nguyễn Dynasty (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 120,
    base_rice_rate: 130,
    base_wood_rate: 110,
    base_stone_rate: 85,
    base_bazan_rate: 31,
    is_capital: false,
    unlock_order: 26,
    unlock_story_day: 58,
  },
  {
    id: 27,
    name: 'Đà Nẵng',
    name_english: 'Da Nang',
    region: 'Central Coast',
    historical_eras: ['Ancient Port (2000 BCE)', 'Champa Port (1000 CE)', 'French Seaport (1800s)', 'War Period (1950s-60s)', 'Modern Hub (1950+)'],
    base_gold_rate: 125,
    base_rice_rate: 100,
    base_wood_rate: 120,
    base_stone_rate: 95,
    base_bazan_rate: 33,
    is_capital: false,
    unlock_order: 27,
    unlock_story_day: 60,
  },
  {
    id: 28,
    name: 'Quảng Nam',
    name_english: 'Quang Nam',
    region: 'Central Coast',
    historical_eras: ['Ancient Port (2000 BCE)', 'Champa Port (1000 CE)', 'Hoi An Trade (1500s)', 'French Indochina (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 115,
    base_rice_rate: 110,
    base_wood_rate: 130,
    base_stone_rate: 80,
    base_bazan_rate: 30,
    is_capital: false,
    unlock_order: 28,
    unlock_story_day: 62,
  },

  // SOUTH CENTRAL COAST (Nam Trung Bộ) - 4 provinces
  {
    id: 29,
    name: 'Quảng Ngãi',
    name_english: 'Quang Ngai',
    region: 'South Central Coast',
    historical_eras: ['Ancient Port (2000 BCE)', 'Champa War (1000 CE)', 'Vietnam Expansion (1600s)', 'French Colony (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 100,
    base_rice_rate: 120,
    base_wood_rate: 120,
    base_stone_rate: 75,
    base_bazan_rate: 28,
    is_capital: false,
    unlock_order: 29,
    unlock_story_day: 64,
  },
  {
    id: 30,
    name: 'Bình Định',
    name_english: 'Binh Dinh',
    region: 'South Central Coast',
    historical_eras: ['Champa Kingdom (1000 BCE)', 'Champa Conquest (1600 CE)', 'Quy Nhơn Port (1700s)', 'French Territory (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 105,
    base_rice_rate: 125,
    base_wood_rate: 110,
    base_stone_rate: 85,
    base_bazan_rate: 29,
    is_capital: false,
    unlock_order: 30,
    unlock_story_day: 66,
  },
  {
    id: 31,
    name: 'Phú Yên',
    name_english: 'Phu Yen',
    region: 'South Central Coast',
    historical_eras: ['Champa Land (1000 BCE)', 'Champa War (1600 CE)', 'Tây Sơn War (1700s)', 'French Indochina (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 95,
    base_rice_rate: 110,
    base_wood_rate: 130,
    base_stone_rate: 80,
    base_bazan_rate: 26,
    is_capital: false,
    unlock_order: 31,
    unlock_story_day: 68,
  },
  {
    id: 32,
    name: 'Khánh Hòa',
    name_english: 'Khanh Hoa',
    region: 'South Central Coast',
    historical_eras: ['Champa Port (1000 BCE)', 'Champa Capital (1300 CE)', 'Vietnam Expansion (1600s)', 'French Resort (1800s)', 'Modern Beach (1950+)'],
    base_gold_rate: 110,
    base_rice_rate: 105,
    base_wood_rate: 140,
    base_stone_rate: 90,
    base_bazan_rate: 32,
    is_capital: false,
    unlock_order: 32,
    unlock_story_day: 70,
  },

  // SOUTHEAST (Đông Nam Bộ) - 6 provinces
  {
    id: 33,
    name: 'Bình Dương (Southeast)',
    name_english: 'Binh Duong SE',
    region: 'Southeast',
    historical_eras: ['Hill Kingdom (2000 BCE)', 'Champa War (1000 CE)', 'Vietnam Expansion (1600s)', 'French Colony (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 100,
    base_rice_rate: 100,
    base_wood_rate: 150,
    base_stone_rate: 70,
    base_bazan_rate: 30,
    is_capital: false,
    unlock_order: 33,
    unlock_story_day: 72,
  },
  {
    id: 34,
    name: 'Ninh Thuận',
    name_english: 'Ninh Thuan',
    region: 'Southeast',
    historical_eras: ['Champa Port (1000 BCE)', 'Champa War (1600 CE)', 'Cham Kingdom (1400s)', 'French Territory (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 90,
    base_rice_rate: 95,
    base_wood_rate: 120,
    base_stone_rate: 100,
    base_bazan_rate: 28,
    is_capital: false,
    unlock_order: 34,
    unlock_story_day: 74,
  },
  {
    id: 35,
    name: 'Bình Thuận',
    name_english: 'Binh Thuan',
    region: 'Southeast',
    historical_eras: ['Champa Land (1000 BCE)', 'Vietnam Conquest (1600 CE)', 'Desert Kingdom (1700s)', 'French Indochina (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 95,
    base_rice_rate: 100,
    base_wood_rate: 110,
    base_stone_rate: 95,
    base_bazan_rate: 27,
    is_capital: false,
    unlock_order: 35,
    unlock_story_day: 76,
  },
  {
    id: 36,
    name: 'Bình Phước',
    name_english: 'Binh Phuoc',
    region: 'Southeast',
    historical_eras: ['Forest Land (2000 BCE)', 'Khmer War (1000 CE)', 'Vietnam Expansion (1600s)', 'French Territory (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 85,
    base_rice_rate: 110,
    base_wood_rate: 150,
    base_stone_rate: 80,
    base_bazan_rate: 25,
    is_capital: false,
    unlock_order: 36,
    unlock_story_day: 78,
  },
  {
    id: 37,
    name: 'Bình Dương',
    name_english: 'Binh Duong',
    region: 'Southeast',
    historical_eras: ['Khmer Kingdom (1000 BCE)', 'Vietnam Expansion (1600s)', 'Nguyễn Dynasty (1800s)', 'French Indochina (1800s)', 'Modern Industrial (1950+)'],
    base_gold_rate: 120,
    base_rice_rate: 100,
    base_wood_rate: 100,
    base_stone_rate: 90,
    base_bazan_rate: 35,
    is_capital: false,
    unlock_order: 37,
    unlock_story_day: 80,
  },
  {
    id: 38,
    name: 'Đồng Nai',
    name_english: 'Dong Nai',
    region: 'Southeast',
    historical_eras: ['Khmer Settlement (1000 BCE)', 'Vietnam Expansion (1600s)', 'Nguyễn Dynasty (1800s)', 'French Port (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 115,
    base_rice_rate: 105,
    base_wood_rate: 120,
    base_stone_rate: 85,
    base_bazan_rate: 33,
    is_capital: false,
    unlock_order: 38,
    unlock_story_day: 82,
  },

  // MEKONG DELTA (Đông Nam Bộ / Mekong) - 13 provinces
  {
    id: 39,
    name: 'Bạc Liêu',
    name_english: 'Bac Lieu',
    region: 'Mekong Delta',
    historical_eras: ['Khmer Water (1000 BCE)', 'Vietnam Expansion (1600s)', 'Water Kingdom (1700s)', 'French Indochina (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 100,
    base_rice_rate: 150,
    base_wood_rate: 90,
    base_stone_rate: 60,
    base_bazan_rate: 24,
    is_capital: false,
    unlock_order: 39,
    unlock_story_day: 84,
  },
  {
    id: 40,
    name: 'Cà Mau',
    name_english: 'Ca Mau',
    region: 'Mekong Delta',
    historical_eras: ['Swamp Kingdom (1000 BCE)', 'Water Frontier (1600s)', 'Pirate Den (1700s)', 'French Colony (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 90,
    base_rice_rate: 160,
    base_wood_rate: 100,
    base_stone_rate: 50,
    base_bazan_rate: 22,
    is_capital: false,
    unlock_order: 40,
    unlock_story_day: 86,
  },
  {
    id: 41,
    name: 'Kiên Giang',
    name_english: 'Kien Giang',
    region: 'Mekong Delta',
    historical_eras: ['Khmer Port (1000 BCE)', 'Vietnam Expansion (1600s)', 'Water Kingdom (1700s)', 'French Territory (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 105,
    base_rice_rate: 145,
    base_wood_rate: 95,
    base_stone_rate: 65,
    base_bazan_rate: 26,
    is_capital: false,
    unlock_order: 41,
    unlock_story_day: 88,
  },
  {
    id: 42,
    name: 'An Giang',
    name_english: 'An Giang',
    region: 'Mekong Delta',
    historical_eras: ['Khmer Water (1000 BCE)', 'Vietnam Expansion (1600s)', 'River Kingdom (1700s)', 'French Indochina (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 100,
    base_rice_rate: 155,
    base_wood_rate: 85,
    base_stone_rate: 55,
    base_bazan_rate: 23,
    is_capital: false,
    unlock_order: 42,
    unlock_story_day: 90,
  },
  {
    id: 43,
    name: 'Chương Mỹ',
    name_english: 'Chuong My',
    region: 'Mekong Delta',
    historical_eras: ['Water Land (1000 BCE)', 'Vietnam Expansion (1600s)', 'Rice Kingdom (1700s)', 'French Colony (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 95,
    base_rice_rate: 160,
    base_wood_rate: 90,
    base_stone_rate: 50,
    base_bazan_rate: 20,
    is_capital: false,
    unlock_order: 43,
    unlock_story_day: 92,
  },
  {
    id: 44,
    name: 'Sóc Trăng',
    name_english: 'Soc Trang',
    region: 'Mekong Delta',
    historical_eras: ['Khmer Temple (1000 BCE)', 'Vietnam Expansion (1600s)', 'Water Kingdom (1700s)', 'French Indochina (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 90,
    base_rice_rate: 155,
    base_wood_rate: 95,
    base_stone_rate: 55,
    base_bazan_rate: 21,
    is_capital: false,
    unlock_order: 44,
    unlock_story_day: 94,
  },
  {
    id: 45,
    name: 'Bến Tre',
    name_english: 'Ben Tre',
    region: 'Mekong Delta',
    historical_eras: ['Coconut Island (1000 BCE)', 'Vietnam Expansion (1600s)', 'Coconut Kingdom (1700s)', 'French Colony (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 100,
    base_rice_rate: 150,
    base_wood_rate: 140,
    base_stone_rate: 50,
    base_bazan_rate: 25,
    is_capital: false,
    unlock_order: 45,
    unlock_story_day: 96,
  },
  {
    id: 46,
    name: 'Trà Vinh',
    name_english: 'Tra Vinh',
    region: 'Mekong Delta',
    historical_eras: ['Khmer Land (1000 BCE)', 'Vietnam Expansion (1600s)', 'Water Kingdom (1700s)', 'French Territory (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 90,
    base_rice_rate: 155,
    base_wood_rate: 100,
    base_stone_rate: 50,
    base_bazan_rate: 22,
    is_capital: false,
    unlock_order: 46,
    unlock_story_day: 98,
  },
  {
    id: 47,
    name: 'Vĩnh Long',
    name_english: 'Vinh Long',
    region: 'Mekong Delta',
    historical_eras: ['Water Land (1000 BCE)', 'Vietnam Expansion (1600s)', 'River Port (1700s)', 'French Indochina (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 95,
    base_rice_rate: 160,
    base_wood_rate: 95,
    base_stone_rate: 55,
    base_bazan_rate: 23,
    is_capital: false,
    unlock_order: 47,
    unlock_story_day: 100,
  },
  {
    id: 48,
    name: 'Tiền Giang',
    name_english: 'Tien Giang',
    region: 'Mekong Delta',
    historical_eras: ['Khmer Water (1000 BCE)', 'Vietnam Expansion (1600s)', 'Rice Kingdom (1700s)', 'French Territory (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 100,
    base_rice_rate: 165,
    base_wood_rate: 90,
    base_stone_rate: 50,
    base_bazan_rate: 24,
    is_capital: false,
    unlock_order: 48,
    unlock_story_day: 102,
  },
  {
    id: 49,
    name: 'Long An',
    name_english: 'Long An',
    region: 'Mekong Delta',
    historical_eras: ['Khmer Land (1000 BCE)', 'Vietnam Expansion (1600s)', 'Water Kingdom (1700s)', 'French Colony (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 105,
    base_rice_rate: 160,
    base_wood_rate: 85,
    base_stone_rate: 55,
    base_bazan_rate: 25,
    is_capital: false,
    unlock_order: 49,
    unlock_story_day: 104,
  },
  {
    id: 50,
    name: 'Hà Tây',
    name_english: 'Ha Tay',
    region: 'Mekong Delta',
    historical_eras: ['Outer Kingdom (1000 BCE)', 'Vietnam Expansion (1600s)', 'Rural Land (1700s)', 'French Territory (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 90,
    base_rice_rate: 150,
    base_wood_rate: 100,
    base_stone_rate: 60,
    base_bazan_rate: 22,
    is_capital: false,
    unlock_order: 50,
    unlock_story_day: 106,
  },
  {
    id: 51,
    name: 'Thành Phố Hồ Chí Minh',
    name_english: 'Ho Chi Minh City',
    region: 'Mekong Delta',
    historical_eras: ['Khmer Port (1000 BCE)', 'Saigon Fortress (1600s)', 'Colonial Saigon (1800s)', 'War Saigon (1950s-60s)', 'Modern Saigon (1975+)'],
    base_gold_rate: 140,
    base_rice_rate: 130,
    base_wood_rate: 110,
    base_stone_rate: 100,
    base_bazan_rate: 40,
    is_capital: false,
    unlock_order: 51,
    unlock_story_day: 108,
  },

  // REMAINING PROVINCES (Fill to 63)
  {
    id: 52,
    name: 'Hưng Yên',
    name_english: 'Hung Yen',
    region: 'Red River Delta',
    historical_eras: ['Ancient Settlement (2000 BCE)', 'Dynasty Period (1000 CE)', 'Medieval Era (1300s)', 'French Indochina (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 100,
    base_rice_rate: 145,
    base_wood_rate: 95,
    base_stone_rate: 70,
    base_bazan_rate: 24,
    is_capital: false,
    unlock_order: 52,
    unlock_story_day: 110,
  },
  {
    id: 53,
    name: 'Hải Dương',
    name_english: 'Hai Duong',
    region: 'Red River Delta',
    historical_eras: ['Coastal Kingdom (2000 BCE)', 'Dynasty Port (1000 CE)', 'Trading Hub (1300s)', 'French Territory (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 105,
    base_rice_rate: 140,
    base_wood_rate: 100,
    base_stone_rate: 75,
    base_bazan_rate: 26,
    is_capital: false,
    unlock_order: 53,
    unlock_story_day: 112,
  },
  {
    id: 54,
    name: 'Nam Định',
    name_english: 'Nam Dinh',
    region: 'Red River Delta',
    historical_eras: ['Ancient Settlement (2000 BCE)', 'Dynasty Capital (1000 CE)', 'Medieval City (1300s)', 'French Colony (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 100,
    base_rice_rate: 155,
    base_wood_rate: 85,
    base_stone_rate: 65,
    base_bazan_rate: 23,
    is_capital: false,
    unlock_order: 54,
    unlock_story_day: 114,
  },
  {
    id: 55,
    name: 'Ninh Bình',
    name_english: 'Ninh Binh',
    region: 'Red River Delta',
    historical_eras: ['Mountain Kingdom (2000 BCE)', 'Dynasty Fort (1000 CE)', 'Limestone Wonder (1300s)', 'French Indochina (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 95,
    base_rice_rate: 135,
    base_wood_rate: 110,
    base_stone_rate: 90,
    base_bazan_rate: 28,
    is_capital: false,
    unlock_order: 55,
    unlock_story_day: 116,
  },
  {
    id: 56,
    name: 'Hòa Bình',
    name_english: 'Hoa Binh',
    region: 'Red River Delta',
    historical_eras: ['Mountain Tribe (2000 BCE)', 'Dynasty Border (1000 CE)', 'Mountain Kingdom (1300s)', 'French Indochina (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 85,
    base_rice_rate: 120,
    base_wood_rate: 140,
    base_stone_rate: 100,
    base_bazan_rate: 26,
    is_capital: false,
    unlock_order: 56,
    unlock_story_day: 118,
  },
  {
    id: 57,
    name: 'Thái Bình',
    name_english: 'Thai Binh',
    region: 'Red River Delta',
    historical_eras: ['Coastal Settlement (2000 BCE)', 'Dynasty Port (1000 CE)', 'Rice Kingdom (1300s)', 'French Territory (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 100,
    base_rice_rate: 160,
    base_wood_rate: 80,
    base_stone_rate: 60,
    base_bazan_rate: 22,
    is_capital: false,
    unlock_order: 57,
    unlock_story_day: 120,
  },
  {
    id: 58,
    name: 'Hậu Giang',
    name_english: 'Hau Giang',
    region: 'Mekong Delta',
    historical_eras: ['Water Land (1000 BCE)', 'Vietnam Expansion (1600s)', 'Rice Kingdom (1700s)', 'French Indochina (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 90,
    base_rice_rate: 160,
    base_wood_rate: 90,
    base_stone_rate: 50,
    base_bazan_rate: 21,
    is_capital: false,
    unlock_order: 58,
    unlock_story_day: 122,
  },
  {
    id: 59,
    name: 'Cần Thơ',
    name_english: 'Can Tho',
    region: 'Mekong Delta',
    historical_eras: ['Khmer Water (1000 BCE)', 'Vietnam Expansion (1600s)', 'River Port (1700s)', 'French Indochina (1800s)', 'Modern Hub (1950+)'],
    base_gold_rate: 110,
    base_rice_rate: 165,
    base_wood_rate: 85,
    base_stone_rate: 55,
    base_bazan_rate: 28,
    is_capital: false,
    unlock_order: 59,
    unlock_story_day: 124,
  },
  {
    id: 60,
    name: 'Gò Công',
    name_english: 'Go Cong',
    region: 'Mekong Delta',
    historical_eras: ['Water Settlement (1000 BCE)', 'Vietnam Expansion (1600s)', 'Water Kingdom (1700s)', 'French Territory (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 95,
    base_rice_rate: 155,
    base_wood_rate: 95,
    base_stone_rate: 55,
    base_bazan_rate: 23,
    is_capital: false,
    unlock_order: 60,
    unlock_story_day: 126,
  },
  {
    id: 61,
    name: 'Cà Mau (South)',
    name_english: 'Ca Mau South',
    region: 'Mekong Delta',
    historical_eras: ['Swamp Frontier (1000 BCE)', 'Vietnam Frontier (1600s)', 'Water Kingdom (1700s)', 'French Colony (1800s)', 'Modern Province (1950+)'],
    base_gold_rate: 85,
    base_rice_rate: 155,
    base_wood_rate: 100,
    base_stone_rate: 50,
    base_bazan_rate: 20,
    is_capital: false,
    unlock_order: 61,
    unlock_story_day: 128,
  },
  {
    id: 62,
    name: 'Vũng Tàu',
    name_english: 'Vung Tau',
    region: 'Southeast',
    historical_eras: ['Coastal Fort (1000 BCE)', 'Vietnam Expansion (1600s)', 'French Fort (1800s)', 'Oil Port (1950s)', 'Modern Resort (1950+)'],
    base_gold_rate: 120,
    base_rice_rate: 95,
    base_wood_rate: 120,
    base_stone_rate: 100,
    base_bazan_rate: 35,
    is_capital: false,
    unlock_order: 62,
    unlock_story_day: 130,
  },
  {
    id: 63,
    name: 'Phú Quốc',
    name_english: 'Phu Quoc',
    region: 'Southeast Islands',
    historical_eras: ['Island Kingdom (1000 BCE)', 'Khmer Island (1000 CE)', 'Vietnamese Island (1600s)', 'French Indochina (1800s)', 'Modern Resort (1950+)'],
    base_gold_rate: 130,
    base_rice_rate: 100,
    base_wood_rate: 130,
    base_stone_rate: 80,
    base_bazan_rate: 38,
    is_capital: false,
    unlock_order: 63,
    unlock_story_day: 132,
  },
]

// Seed provinces to database
export async function seedProvinces() {
  const client = new Client({
    connectionString: process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:11003/katagame',
  })

  try {
    await client.connect()
    console.log('📌 Seeding 63 Vietnamese provinces...')

    // Clear existing provinces
    await client.query('TRUNCATE TABLE provinces CASCADE')
    console.log('✅ Cleared existing provinces')

    // Insert all provinces
    for (const province of PROVINCES_DATA) {
      const query = `
        INSERT INTO provinces (
          id, name, name_english, region,
          historical_eras,
          base_gold_rate, base_rice_rate, base_wood_rate,
          base_stone_rate, base_bazan_rate,
          is_capital, unlock_order, unlock_story_day
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
        )
      `

      await client.query(query, [
        province.id,
        province.name,
        province.name_english,
        province.region,
        JSON.stringify(province.historical_eras),
        province.base_gold_rate,
        province.base_rice_rate,
        province.base_wood_rate,
        province.base_stone_rate,
        province.base_bazan_rate,
        province.is_capital,
        province.unlock_order,
        province.unlock_story_day,
      ])
    }

    console.log(`✅ Successfully seeded ${PROVINCES_DATA.length} provinces`)

    // Verify
    const result = await client.query('SELECT COUNT(*) as count FROM provinces')
    console.log(`✅ Database contains ${result.rows[0].count} provinces`)
  } catch (error: any) {
    console.error('❌ Error seeding provinces:', error.message)
    throw error
  } finally {
    await client.end()
  }
}

// Run if called directly
if (require.main === module) {
  seedProvinces().catch(console.error)
}
